### ISSUE TITLE
Textual depends on Printable?

### ISSUE THREAD

**Issue by goertzenator** [mvv/data-textual#5]
A design question: why does Textual require Printable?

I often have to implement a dummy Printable instance just so I can get to Textual.  Not a huge deal, but if there's a good explanation I would like to know it.  Thanks!

BTW, data-textual has been in my prelude for a few years now.  An excellent library.

**Comment by mvv** [comment]
Thank you for the kind words. Textual was designed with human-writable configuration values as the primary use case, and most of the time you want to be able to log what you've configured. Hence the Printable dependency.

**Comment by goertzenator** [comment]
I see.  So there will be application code with a `Textual a` constraint that will then use `Printable` methods.

That got me thinking... how would you feel about something like this?  

```
-- | Instances of this class automatically get a Textual instance and a dummy Printable instance.
class TextualOnly α where
  textualOnly :: (Monad μ, CharParsing μ) => μ α

instance (TextualOnly α) => Printable α where
  print = undefined

instance (TextualOnly α) => Textual α where
  textual = textualOnly
```

For use cases like mine I would implement `TextualOnly` and not have to worry about a dummy `Printable`.

**Comment by mvv** [comment]
Could you give some examples of your data types and a bit of the use case context?

**Comment by goertzenator** [comment]
Hmmm.  I looked in all the places that had dummy `Printable` instances only to find that I eventually needed real `Printable` instances at some point.  I guess the `TextualOnly` idea isn't that important.
